default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: postgresql://user:password@127.0.0.1:5432/app_development

test:
  <<: *default
  database: postgresql://user:password@127.0.0.1:5432/app_test
